const osData = [
  { name: "Windows 11", family: "Windows", users: 850, sharePercent: 32.1, sharePercentOS: 45.2 },
  { name: "Windows 10", family: "Windows", users: 750, sharePercent: 28.3, sharePercentOS: 39.9 },
  { name: "Windows 7", family: "Windows", users: 120, sharePercent: 4.5, sharePercentOS: 6.4 },
  { name: "Windows 8.1", family: "Windows", users: 60, sharePercent: 2.3, sharePercentOS: 3.2 },
  { name: "Windows XP", family: "Windows", users: 15, sharePercent: 0.6, sharePercentOS: 0.8 },
  { name: "Windows Server", family: "Windows", users: 85, sharePercent: 3.2, sharePercentOS: 4.5 },
  { name: "macOS Sonoma", family: "macOS", users: 95, sharePercent: 3.6, sharePercentOS: 28.8 },
  { name: "macOS Ventura", family: "macOS", users: 85, sharePercent: 3.2, sharePercentOS: 25.8 },
  { name: "macOS Monterey", family: "macOS", users: 65, sharePercent: 2.5, sharePercentOS: 19.7 },
  { name: "macOS Big Sur", family: "macOS", users: 45, sharePercent: 1.7, sharePercentOS: 13.6 },
  { name: "macOS Catalina", family: "macOS", users: 25, sharePercent: 0.9, sharePercentOS: 7.6 },
  { name: "macOS Mojave", family: "macOS", users: 15, sharePercent: 0.6, sharePercentOS: 4.5 },
  { name: "Ubuntu", family: "Linux", users: 45, sharePercent: 1.7, sharePercentOS: 25.0 },
  { name: "Linux Mint", family: "Linux", users: 28, sharePercent: 1.1, sharePercentOS: 15.6 },
  { name: "Debian", family: "Linux", users: 25, sharePercent: 0.9, sharePercentOS: 13.9 },
  { name: "Fedora", family: "Linux", users: 18, sharePercent: 0.7, sharePercentOS: 10.0 },
  { name: "Arch Linux", family: "Linux", users: 12, sharePercent: 0.5, sharePercentOS: 6.7 },
  { name: "openSUSE", family: "Linux", users: 8, sharePercent: 0.3, sharePercentOS: 4.4 },
  { name: "Manjaro", family: "Linux", users: 7, sharePercent: 0.3, sharePercentOS: 3.9 },
  { name: "CentOS", family: "Linux", users: 6, sharePercent: 0.2, sharePercentOS: 3.3 },
  { name: "Pop!_OS", family: "Linux", users: 5, sharePercent: 0.2, sharePercentOS: 2.8 },
  { name: "Elementary OS", family: "Linux", users: 4, sharePercent: 0.2, sharePercentOS: 2.2 },
  { name: "Zorin OS", family: "Linux", users: 3, sharePercent: 0.1, sharePercentOS: 1.7 },
  { name: "Kali Linux", family: "Linux", users: 3, sharePercent: 0.1, sharePercentOS: 1.7 },
  { name: "MX Linux", family: "Linux", users: 3, sharePercent: 0.1, sharePercentOS: 1.7 },
  { name: "Gentoo", family: "Linux", users: 2, sharePercent: 0.1, sharePercentOS: 1.1 },
  { name: "Slackware", family: "Linux", users: 1, sharePercent: 0.04, sharePercentOS: 0.6 },
  { name: "Other Linux", family: "Linux", users: 10, sharePercent: 0.4, sharePercentOS: 5.6 }
];